#pragma once

#define CODEX_DECK_FIRMWARE_VERSION "0.6.0-stage-f-stt-codex"
#define CODEX_DECK_DEVICE_NAME "waveshare-deck-349"

#define CODEX_DECK_MAX_SLOTS 5
#define CODEX_DECK_WIFI_TIMEOUT_MS 15000
#define CODEX_DECK_HTTP_TIMEOUT_MS 5000
#define CODEX_DECK_AUDIO_UPLOAD_TIMEOUT_MS 15000
#define CODEX_DECK_SLOT_REFRESH_MS 30000
#define CODEX_DECK_JOB_POLL_MS 3000

#define CODEX_DECK_AUDIO_SAMPLE_RATE 24000
#define CODEX_DECK_AUDIO_CHANNELS 2
#define CODEX_DECK_AUDIO_BITS_PER_SAMPLE 16
#define CODEX_DECK_AUDIO_MAX_MS 15000
#define CODEX_DECK_AUDIO_MIN_MS 300
#define CODEX_DECK_AUDIO_CHUNK_BYTES 4096

#ifndef DECK_HARDWARE_VARIANT
#define DECK_HARDWARE_VARIANT 2
#endif

#if DECK_HARDWARE_VARIANT == 1
#define DECK_HARDWARE_VARIANT_TEXT "V1"
#elif DECK_HARDWARE_VARIANT == 2
#define DECK_HARDWARE_VARIANT_TEXT "V2"
#else
#error "DECK_HARDWARE_VARIANT must be 1 or 2"
#endif
