[platformio]
default_envs = waveshare_deck_349
packages_dir = .pio/packages

[env]
platform = https://github.com/Seeed-Studio/platform-seeedboards.git#9e97e019ace102952d03f299a94ee8353f5a8043
board = seeed-xiao-esp32-s3-sense
framework = arduino
monitor_speed = 115200
upload_speed = 921600

board_build.flash_size = 16MB
board_build.partitions = partitions/deck_16m_no_ota.csv
board_build.arduino.memory_type = qio_opi

lib_deps =
    lvgl/lvgl@9.3.0
    bblanchon/ArduinoJson@7.4.3

platform_packages =
    tool-esptoolpy@https://files.seeedstudio.com/arduino/platformio/esptoolpy-v5.1.2.zip

[deck_common]
build_flags =
    -D BOARD_HAS_PSRAM
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D LV_CONF_INCLUDE_SIMPLE
    -D DECK_HARDWARE_VARIANT=2
    -I include
    -I src
    -I src/board
    -I src/axs15231b
    -I src/tca9554
    -I src/touch
    -I src/lcd_bl_bsp
    -I src/codec_board
    -I src/esp_codec_dev
    -I src/esp_codec_dev/include
    -I src/esp_codec_dev/interface
    -I src/esp_codec_dev/device/include
    -I src/esp_codec_dev/device/priv_include

[env:waveshare_deck_349]
build_flags =
    ${deck_common.build_flags}
    -D CORE_DEBUG_LEVEL=3
    -D DECK_VERBOSE_LOGS=1

[env:waveshare_deck_349_release]
build_flags =
    ${deck_common.build_flags}
    -D CORE_DEBUG_LEVEL=1
    -D LOG_LOCAL_LEVEL=ESP_LOG_WARN
    -D DECK_VERBOSE_LOGS=0
